top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/mappers
builddir     = /home/jz/Documents/chainmux-src/modules/mappers
VPATH        = /home/jz/Documents/chainmux-src/modules/mappers

include $(top_srcdir)/build/special.mk

