/*
 * modules.c --- automatically generated by Apache
 * configuration script.  DO NOT HAND EDIT!!!!!
 */

#include "ap_config.h"
#include "httpd.h"
#include "http_config.h"

extern module core_module;
extern module authn_file_module;
extern module authn_dbm_module;
extern module authn_anon_module;
extern module authn_dbd_module;
extern module authn_socache_module;
extern module authn_core_module;
extern module authz_host_module;
extern module authz_groupfile_module;
extern module authz_user_module;
extern module authz_dbm_module;
extern module authz_owner_module;
extern module authz_dbd_module;
extern module authz_core_module;
extern module access_compat_module;
extern module auth_basic_module;
extern module auth_form_module;
extern module auth_digest_module;
extern module allowmethods_module;
extern module file_cache_module;
extern module cache_module;
extern module cache_disk_module;
extern module cache_socache_module;
extern module socache_shmcb_module;
extern module socache_dbm_module;
extern module socache_memcache_module;
extern module so_module;
extern module watchdog_module;
extern module macro_module;
extern module dbd_module;
extern module dumpio_module;
extern module echo_module;
extern module buffer_module;
extern module data_module;
extern module ratelimit_module;
extern module reqtimeout_module;
extern module ext_filter_module;
extern module request_module;
extern module include_module;
extern module filter_module;
extern module reflector_module;
extern module substitute_module;
extern module sed_module;
extern module charset_lite_module;
extern module http_module;
extern module mime_module;
extern module log_config_module;
extern module log_debug_module;
extern module log_forensic_module;
extern module logio_module;
extern module env_module;
extern module mime_magic_module;
extern module expires_module;
extern module headers_module;
extern module usertrack_module;
extern module unique_id_module;
extern module setenvif_module;
extern module version_module;
extern module remoteip_module;
extern module proxy_module;
extern module proxy_connect_module;
extern module proxy_ftp_module;
extern module proxy_http_module;
extern module proxy_fcgi_module;
extern module proxy_scgi_module;
extern module proxy_uwsgi_module;
extern module proxy_fdpass_module;
extern module proxy_wstunnel_module;
extern module proxy_ajp_module;
extern module proxy_balancer_module;
extern module proxy_express_module;
extern module proxy_hcheck_module;
extern module session_module;
extern module session_cookie_module;
extern module session_dbd_module;
extern module slotmem_shm_module;
extern module slotmem_plain_module;
extern module dialup_module;
extern module lbmethod_byrequests_module;
extern module lbmethod_bytraffic_module;
extern module lbmethod_bybusyness_module;
extern module lbmethod_heartbeat_module;
extern module mpm_event_module;
extern module unixd_module;
extern module heartbeat_module;
extern module heartmonitor_module;
extern module dav_module;
extern module status_module;
extern module autoindex_module;
extern module asis_module;
extern module info_module;
extern module cgid_module;
extern module dav_fs_module;
extern module dav_lock_module;
extern module vhost_alias_module;
extern module negotiation_module;
extern module dir_module;
extern module actions_module;
extern module speling_module;
extern module userdir_module;
extern module alias_module;
extern module rewrite_module;

/*
 *  Modules which implicitly form the
 *  list of activated modules on startup,
 *  i.e. these are the modules which are
 *  initially linked into the Apache processing
 *  [extendable under run-time via AddModule]
 */
module *ap_prelinked_modules[] = {
  &core_module,
  &authn_file_module,
  &authn_dbm_module,
  &authn_anon_module,
  &authn_dbd_module,
  &authn_socache_module,
  &authn_core_module,
  &authz_host_module,
  &authz_groupfile_module,
  &authz_user_module,
  &authz_dbm_module,
  &authz_owner_module,
  &authz_dbd_module,
  &authz_core_module,
  &access_compat_module,
  &auth_basic_module,
  &auth_form_module,
  &auth_digest_module,
  &allowmethods_module,
  &file_cache_module,
  &cache_module,
  &cache_disk_module,
  &cache_socache_module,
  &socache_shmcb_module,
  &socache_dbm_module,
  &socache_memcache_module,
  &so_module,
  &watchdog_module,
  &macro_module,
  &dbd_module,
  &dumpio_module,
  &echo_module,
  &buffer_module,
  &data_module,
  &ratelimit_module,
  &reqtimeout_module,
  &ext_filter_module,
  &request_module,
  &include_module,
  &filter_module,
  &reflector_module,
  &substitute_module,
  &sed_module,
  &charset_lite_module,
  &http_module,
  &mime_module,
  &log_config_module,
  &log_debug_module,
  &log_forensic_module,
  &logio_module,
  &env_module,
  &mime_magic_module,
  &expires_module,
  &headers_module,
  &usertrack_module,
  &unique_id_module,
  &setenvif_module,
  &version_module,
  &remoteip_module,
  &proxy_module,
  &proxy_connect_module,
  &proxy_ftp_module,
  &proxy_http_module,
  &proxy_fcgi_module,
  &proxy_scgi_module,
  &proxy_uwsgi_module,
  &proxy_fdpass_module,
  &proxy_wstunnel_module,
  &proxy_ajp_module,
  &proxy_balancer_module,
  &proxy_express_module,
  &proxy_hcheck_module,
  &session_module,
  &session_cookie_module,
  &session_dbd_module,
  &slotmem_shm_module,
  &slotmem_plain_module,
  &dialup_module,
  &lbmethod_byrequests_module,
  &lbmethod_bytraffic_module,
  &lbmethod_bybusyness_module,
  &lbmethod_heartbeat_module,
  &mpm_event_module,
  &unixd_module,
  &heartbeat_module,
  &heartmonitor_module,
  &dav_module,
  &status_module,
  &autoindex_module,
  &asis_module,
  &info_module,
  &cgid_module,
  &dav_fs_module,
  &dav_lock_module,
  &vhost_alias_module,
  &negotiation_module,
  &dir_module,
  &actions_module,
  &speling_module,
  &userdir_module,
  &alias_module,
  &rewrite_module,
  NULL
};

/*
 *  We need the symbols as strings for <IfModule> containers
 */

ap_module_symbol_t ap_prelinked_module_symbols[] = {
  {"core_module", &core_module},
  {"authn_file_module", &authn_file_module},
  {"authn_dbm_module", &authn_dbm_module},
  {"authn_anon_module", &authn_anon_module},
  {"authn_dbd_module", &authn_dbd_module},
  {"authn_socache_module", &authn_socache_module},
  {"authn_core_module", &authn_core_module},
  {"authz_host_module", &authz_host_module},
  {"authz_groupfile_module", &authz_groupfile_module},
  {"authz_user_module", &authz_user_module},
  {"authz_dbm_module", &authz_dbm_module},
  {"authz_owner_module", &authz_owner_module},
  {"authz_dbd_module", &authz_dbd_module},
  {"authz_core_module", &authz_core_module},
  {"access_compat_module", &access_compat_module},
  {"auth_basic_module", &auth_basic_module},
  {"auth_form_module", &auth_form_module},
  {"auth_digest_module", &auth_digest_module},
  {"allowmethods_module", &allowmethods_module},
  {"file_cache_module", &file_cache_module},
  {"cache_module", &cache_module},
  {"cache_disk_module", &cache_disk_module},
  {"cache_socache_module", &cache_socache_module},
  {"socache_shmcb_module", &socache_shmcb_module},
  {"socache_dbm_module", &socache_dbm_module},
  {"socache_memcache_module", &socache_memcache_module},
  {"so_module", &so_module},
  {"watchdog_module", &watchdog_module},
  {"macro_module", &macro_module},
  {"dbd_module", &dbd_module},
  {"dumpio_module", &dumpio_module},
  {"echo_module", &echo_module},
  {"buffer_module", &buffer_module},
  {"data_module", &data_module},
  {"ratelimit_module", &ratelimit_module},
  {"reqtimeout_module", &reqtimeout_module},
  {"ext_filter_module", &ext_filter_module},
  {"request_module", &request_module},
  {"include_module", &include_module},
  {"filter_module", &filter_module},
  {"reflector_module", &reflector_module},
  {"substitute_module", &substitute_module},
  {"sed_module", &sed_module},
  {"charset_lite_module", &charset_lite_module},
  {"http_module", &http_module},
  {"mime_module", &mime_module},
  {"log_config_module", &log_config_module},
  {"log_debug_module", &log_debug_module},
  {"log_forensic_module", &log_forensic_module},
  {"logio_module", &logio_module},
  {"env_module", &env_module},
  {"mime_magic_module", &mime_magic_module},
  {"expires_module", &expires_module},
  {"headers_module", &headers_module},
  {"usertrack_module", &usertrack_module},
  {"unique_id_module", &unique_id_module},
  {"setenvif_module", &setenvif_module},
  {"version_module", &version_module},
  {"remoteip_module", &remoteip_module},
  {"proxy_module", &proxy_module},
  {"proxy_connect_module", &proxy_connect_module},
  {"proxy_ftp_module", &proxy_ftp_module},
  {"proxy_http_module", &proxy_http_module},
  {"proxy_fcgi_module", &proxy_fcgi_module},
  {"proxy_scgi_module", &proxy_scgi_module},
  {"proxy_uwsgi_module", &proxy_uwsgi_module},
  {"proxy_fdpass_module", &proxy_fdpass_module},
  {"proxy_wstunnel_module", &proxy_wstunnel_module},
  {"proxy_ajp_module", &proxy_ajp_module},
  {"proxy_balancer_module", &proxy_balancer_module},
  {"proxy_express_module", &proxy_express_module},
  {"proxy_hcheck_module", &proxy_hcheck_module},
  {"session_module", &session_module},
  {"session_cookie_module", &session_cookie_module},
  {"session_dbd_module", &session_dbd_module},
  {"slotmem_shm_module", &slotmem_shm_module},
  {"slotmem_plain_module", &slotmem_plain_module},
  {"dialup_module", &dialup_module},
  {"lbmethod_byrequests_module", &lbmethod_byrequests_module},
  {"lbmethod_bytraffic_module", &lbmethod_bytraffic_module},
  {"lbmethod_bybusyness_module", &lbmethod_bybusyness_module},
  {"lbmethod_heartbeat_module", &lbmethod_heartbeat_module},
  {"mpm_event_module", &mpm_event_module},
  {"unixd_module", &unixd_module},
  {"heartbeat_module", &heartbeat_module},
  {"heartmonitor_module", &heartmonitor_module},
  {"dav_module", &dav_module},
  {"status_module", &status_module},
  {"autoindex_module", &autoindex_module},
  {"asis_module", &asis_module},
  {"info_module", &info_module},
  {"cgid_module", &cgid_module},
  {"dav_fs_module", &dav_fs_module},
  {"dav_lock_module", &dav_lock_module},
  {"vhost_alias_module", &vhost_alias_module},
  {"negotiation_module", &negotiation_module},
  {"dir_module", &dir_module},
  {"actions_module", &actions_module},
  {"speling_module", &speling_module},
  {"userdir_module", &userdir_module},
  {"alias_module", &alias_module},
  {"rewrite_module", &rewrite_module},
  {NULL, NULL}
};

/*
 *  Modules which initially form the
 *  list of available modules on startup,
 *  i.e. these are the modules which are
 *  initially loaded into the Apache process
 *  [extendable under run-time via LoadModule]
 */
module *ap_preloaded_modules[] = {
  &core_module,
  &authn_file_module,
  &authn_dbm_module,
  &authn_anon_module,
  &authn_dbd_module,
  &authn_socache_module,
  &authn_core_module,
  &authz_host_module,
  &authz_groupfile_module,
  &authz_user_module,
  &authz_dbm_module,
  &authz_owner_module,
  &authz_dbd_module,
  &authz_core_module,
  &access_compat_module,
  &auth_basic_module,
  &auth_form_module,
  &auth_digest_module,
  &allowmethods_module,
  &file_cache_module,
  &cache_module,
  &cache_disk_module,
  &cache_socache_module,
  &socache_shmcb_module,
  &socache_dbm_module,
  &socache_memcache_module,
  &so_module,
  &watchdog_module,
  &macro_module,
  &dbd_module,
  &dumpio_module,
  &echo_module,
  &buffer_module,
  &data_module,
  &ratelimit_module,
  &reqtimeout_module,
  &ext_filter_module,
  &request_module,
  &include_module,
  &filter_module,
  &reflector_module,
  &substitute_module,
  &sed_module,
  &charset_lite_module,
  &http_module,
  &mime_module,
  &log_config_module,
  &log_debug_module,
  &log_forensic_module,
  &logio_module,
  &env_module,
  &mime_magic_module,
  &expires_module,
  &headers_module,
  &usertrack_module,
  &unique_id_module,
  &setenvif_module,
  &version_module,
  &remoteip_module,
  &proxy_module,
  &proxy_connect_module,
  &proxy_ftp_module,
  &proxy_http_module,
  &proxy_fcgi_module,
  &proxy_scgi_module,
  &proxy_uwsgi_module,
  &proxy_fdpass_module,
  &proxy_wstunnel_module,
  &proxy_ajp_module,
  &proxy_balancer_module,
  &proxy_express_module,
  &proxy_hcheck_module,
  &session_module,
  &session_cookie_module,
  &session_dbd_module,
  &slotmem_shm_module,
  &slotmem_plain_module,
  &dialup_module,
  &lbmethod_byrequests_module,
  &lbmethod_bytraffic_module,
  &lbmethod_bybusyness_module,
  &lbmethod_heartbeat_module,
  &mpm_event_module,
  &unixd_module,
  &heartbeat_module,
  &heartmonitor_module,
  &dav_module,
  &status_module,
  &autoindex_module,
  &asis_module,
  &info_module,
  &cgid_module,
  &dav_fs_module,
  &dav_lock_module,
  &vhost_alias_module,
  &negotiation_module,
  &dir_module,
  &actions_module,
  &speling_module,
  &userdir_module,
  &alias_module,
  &rewrite_module,
  NULL
};

