top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/metadata
builddir     = /home/jz/Documents/chainmux-src/modules/metadata
VPATH        = /home/jz/Documents/chainmux-src/modules/metadata

include $(top_srcdir)/build/special.mk

