top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/dav/fs
builddir     = /home/jz/Documents/chainmux-src/modules/dav/fs
VPATH        = /home/jz/Documents/chainmux-src/modules/dav/fs
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
