top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/loggers
builddir     = /home/jz/Documents/chainmux-src/modules/loggers
VPATH        = /home/jz/Documents/chainmux-src/modules/loggers

include $(top_srcdir)/build/special.mk

