top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/generators
builddir     = /home/jz/Documents/chainmux-src/modules/generators
VPATH        = /home/jz/Documents/chainmux-src/modules/generators

include $(top_srcdir)/build/special.mk

