top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/echo
builddir     = /home/jz/Documents/chainmux-src/modules/echo
VPATH        = /home/jz/Documents/chainmux-src/modules/echo

include $(top_srcdir)/build/special.mk

