top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/filters
builddir     = /home/jz/Documents/chainmux-src/modules/filters
VPATH        = /home/jz/Documents/chainmux-src/modules/filters

include $(top_srcdir)/build/special.mk

