top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/aaa
builddir     = /home/jz/Documents/chainmux-src/modules/aaa
VPATH        = /home/jz/Documents/chainmux-src/modules/aaa

include $(top_srcdir)/build/special.mk

