top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/server/mpm/event
builddir     = /home/jz/Documents/chainmux-src/server/mpm/event
VPATH        = /home/jz/Documents/chainmux-src/server/mpm/event
include $(top_srcdir)/build/special.mk
