top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/cache
builddir     = /home/jz/Documents/chainmux-src/modules/cache
VPATH        = /home/jz/Documents/chainmux-src/modules/cache

include $(top_srcdir)/build/special.mk

