top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/os
builddir     = /home/jz/Documents/chainmux-src/os
VPATH        = /home/jz/Documents/chainmux-src/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
