top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/proxy
builddir     = /home/jz/Documents/chainmux-src/modules/proxy
VPATH        = /home/jz/Documents/chainmux-src/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
#SUBDIRS = balancers
include $(top_srcdir)/build/special.mk
