top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/arch/unix
builddir     = /home/jz/Documents/chainmux-src/modules/arch/unix
VPATH        = /home/jz/Documents/chainmux-src/modules/arch/unix

include $(top_srcdir)/build/special.mk

