top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/core
builddir     = /home/jz/Documents/chainmux-src/modules/core
VPATH        = /home/jz/Documents/chainmux-src/modules/core

include $(top_srcdir)/build/special.mk

