top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/modules/http
builddir     = /home/jz/Documents/chainmux-src/modules/http
VPATH        = /home/jz/Documents/chainmux-src/modules/http

include $(top_srcdir)/build/special.mk

