top_srcdir   = /home/jz/Documents/chainmux-src
top_builddir = /home/jz/Documents/chainmux-src
srcdir       = /home/jz/Documents/chainmux-src/server/mpm
builddir     = /home/jz/Documents/chainmux-src/server/mpm
VPATH        = /home/jz/Documents/chainmux-src/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
